### ISSUE TITLE
freqshift~

### ISSUE THREAD

**Issue by porres** [electrickery/pd-sigpack#2] opened 2017-03-04 01:06 UTC
howdy, [freqshift~] is based on this ladspa plugin ( bode shifter 1431: http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html#id1431 ), right? I think it's supposed to be a frequency shifter just like pd vanilla's extra complex-mod~ object, but it sounds really "worse"/more distorted, so is it really supposed to be like that? Try it with a sinusoid and you'll be able to hear how sigpack/freqshift~ really distorts it.

Seems quite unlikely, and maybe we should test the plugin, to check how the original works... 

cheers

**Comment by electrickery** [comment] 2017-03-04 10:00
The distortion is caused by a discontinuity at the start of the block. Not a level issue, but the speed with which a buffer (either the delay or sinus buffer) is read out.
One difference with complex-mod~ is that it has the hilbert transform internally and that it emulates a Bode/Moog ringmodulator.

Found the structure of the object insufficient for a proper frequency shifter object and fixing it would break compatibility of the current (incorrect) behaviour and duplicate other existing abstractions/objects. So I won't fix the current behaviour.

I'll add this to the help-patch:
"This object produces a distorted frequency shift and is only kept for backward compatibility. See Pure Data/3.audio.examples/H09.ssb.modulation.pd for a working frequency shifter."

**Closed as completed** 2022-11-28 20:41 UTC
